# Site settings
title: Nordgedanken Projects
description: A small portfolio
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Nordgedanken
user_description: Production foused FOSS coded by MTRNord
user_title: Free OpenSource Software
email: info@nordgedanken.de
twitter_username: mtrnord
github_username:  Nordgedanken
#gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
